version: '3'
services:
  postgres:
    image: postgres:9.5
    environment:
      - "POSTGRES_USER=mapping_viz"
      - "POSTGRES_PASSWORD=mapping_viz"
    ports:
      - "5432:5432"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/src
    environment:
      - "PGUSER=mapping_viz"
      - "PGPASSWORD=mapping_viz"
      - "PGHOST=pg"
    links:
      - postgres:pg